version: '3.9'

networks:
  bridge81:
    driver: bridge

services:
  proxy:
    image: nginx-basic-auth
    networks:
      - bridge81
    environment:
      - BASIC_USERNAME=webos
      - BASIC_PASSWORD=20090606webos
      - FORWARD_HOST=wrp
      - FORWARD_PORT=8080
    ports:
      - "81:80"
    restart: unless-stopped

  wrp:
    image: tenox7/wrp
    networks:
      - bridge81
    expose:
      - 8080
    restart: unless-stopped
